---
- name: download emudeck
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Download (but not run or install) the EmuDeck installer
      get_url:
        url: https://www.emudeck.com/EmuDeck.desktop
        dest: /home/deck/Desktop/EmuDeck.desktop
